### PR TITLE
[feature] Introduce clap based argument parser in place of argh

### PR DESCRIPTION
**Pull request by TheBearodactyl**

### CODE REVIEW

**Comment by bnjbvr** [comment]
Hi, thanks for the PR, but what's the motivation? argh has been working nicely for me so far, and I'm not sure to see what clap would bring more?

**Comment by TheBearodactyl** [comment]
> Hi, thanks for the PR, but what's the motivation? argh has been working nicely for me so far, and I'm not sure to see what clap would bring more?

This is mostly just a way to improve developer experience. More people work with clap, so it'd be easier for people to make pr's. Also, equally as important (not really), it doesn't require you to specify whether an arg is positional or not, so it's very convenient. Another reason is because with clap, you can organize the output of the help flag more easily

**Comment by TheBearodactyl** [comment]
i just realized the pr is marked as a draft, and now i'm questioning GitHubs sanity

**Comment by bnjbvr** [comment]
> This is mostly just a way to improve developer experience. More people work with clap, so it'd be easier for people to make pr's. Also, equally as important (not really), it doesn't require you to specify whether an arg is positional or not (just a small qol improvement). Another reason is because with clap, you can organize the output of the help flag more easily

Yeah sorry, this is not compelling enough to me to justify the weight of clap. I think `argh` is sufficient for the low number of arguments that `cargo-machete` has, and it's nice in that it has fewer dependencies etc.

Thanks for your PR, though! Next time feel free to bring up your idea in an issue before implementing it :-)

**Comment by TheBearodactyl** [comment]
> > This is mostly just a way to improve developer experience. More people work with clap, so it'd be easier for people to make pr's. Also, equally as important (not really), it doesn't require you to specify whether an arg is positional or not (just a small qol improvement). Another reason is because with clap, you can organize the output of the help flag more easily
> 
> Yeah sorry, this is not compelling enough to me to justify the weight of clap. I think `argh` is sufficient for the low number of arguments that `cargo-machete` has, and it's nice in that it has fewer dependencies etc.
> 
> Thanks for your PR, though! Next time feel free to bring up your idea in an issue before implementing it :-)

fair :D

**Pull request closed without merging**
