### PR TITLE
Add workspace ignore list

### LINKED ISSUE #56: Add ignore list in workspace Cargo.toml
It would be great to have an equivalent to `[package.metadata.cargo-machete]` inside a workspace main `Cargo.toml` to ignore false positive dependencies present in lots of packages of a same workspace.

### PR DESCRIPTION
**Pull request by nanocryk**
Fixes #56

### CODE REVIEW

**Comment by nanocryk** [comment]
Could you take a look when you have time @bnjbvr ? :)

**Comment by bnjbvr** [comment]
Yep, sorry for the slow response time! Last week was a bit hectic. I will try to take a look this week.

**Comment by nanocryk** [comment]
Hmm one issue I now encounter is that if I list a package to be ignore in the workspace, if in some crate it is indeed detected as used I have a warning. So maybe it would be better to store the workspace list separately so that no warnings are generated from them?

**Comment by nanocryk** [comment]
Made the change I commented about above :)

**Review by bnjbvr — APPROVED** [review]
Thanks for adding a test too! looks good to me, and the new syntax and ignore rules make sense to me.

**Pull request merged**
